name: xen_facebook_reaction
description: facebook like reaction emoji, based on animated_emoji flutter package
version: 0.0.1
homepage: none

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
